[package]
name = "circle-eight"
version = "0.1.0"
authors = ["Alex Jones <alexjonestech@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "*"
rand = "*"
